// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dociimlweexksfbvadpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY2lpbWx3ZWV4a3NmYnZhZHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDUzNDksImV4cCI6MjA3MzQyMTM0OX0.MR-chEFAbzp6iV-8LhS5QKF5-wYDJC7w2WU_eLMDJWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);